version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/home/user/app
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5


  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database_init.sql:/docker-entrypoint-initdb.d/database_init.sql
    ports:
      - 5432:5432