version: '3.8'
services:
  app:
    build:
      # context: .
      dockerfile: ./build/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      POSTGRES_HOST: postgres
      RABBIT_MQ_URL: amqp://rabbitmq:5672
    volumes:
      - ./:/home/user/app
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672